name: tealseed_chat
description: "Simple solution for IM chat"
version: 0.0.1
repository: https://github.com/Tealseed-Lab/tealseed_chat
issue_tracker: https://github.com/Tealseed-Lab/tealseed_chat/issues

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.7
  image_picker: ^1.1.2
  logger: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  mobx_codegen: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  assets:
    - assets/svg/input/
