name: simple_chat
description: "Simple solution for IM chat & AI bot chat"
version: 0.0.7
repository: https://github.com/Tealseed-Lab/simple_chat
issue_tracker: https://github.com/Tealseed-Lab/simple_chat/issues

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.7
  image_picker: ^1.1.2
  logger: ^2.4.0
  lottie: ^3.1.2
  uuid: ^4.5.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  mobx_codegen: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  assets:
    - assets/svg/input/
    - assets/svg/chat/
    - assets/lottie/